spring:
  application:
    name: rent-property
  datasource:
    url: jdbc:postgresql://localhost:5432/jee
    username: jee
    password: jee
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8081
